// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARC0r9anm6FpSMwjRvTYRBda0KZs_UgmA',
    appId: '1:164833709543:web:e57c0a437bafa8eb8cc142',
    messagingSenderId: '164833709543',
    projectId: 'reddit-462ee',
    authDomain: 'reddit-462ee.firebaseapp.com',
    storageBucket: 'reddit-462ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDke2u5xsB2vEMa5QVtClePgh2-qQC5Uxk',
    appId: '1:164833709543:android:8890f493d1def04e8cc142',
    messagingSenderId: '164833709543',
    projectId: 'reddit-462ee',
    storageBucket: 'reddit-462ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ciTtoW4aDRfdqTdd5U1cgsDcV3e5gVs',
    appId: '1:164833709543:ios:4c78b75dfb4725748cc142',
    messagingSenderId: '164833709543',
    projectId: 'reddit-462ee',
    storageBucket: 'reddit-462ee.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARC0r9anm6FpSMwjRvTYRBda0KZs_UgmA',
    appId: '1:164833709543:web:eedec870338c119d8cc142',
    messagingSenderId: '164833709543',
    projectId: 'reddit-462ee',
    authDomain: 'reddit-462ee.firebaseapp.com',
    storageBucket: 'reddit-462ee.appspot.com',
  );
}
